const EMP_GET_CATEGORY = "EMP_GET_CATEGORY";
const EMP_SEARCH_NAME = "EMP_SEARCH_NAME";
const EMP_SEARCH_DEPT = "EMP_SEARCH_DEPT";
const EMP_SEARCH_TITLE = "EMP_SEARCH_TITLE";

const EMP_RANK_PERIOD = "EMP_RANK_PERIOD";
const EMP_RANK_SALARY = "EMP_RANK_SALARY";
const EMP_HISTORY = "EMP_HISTORY";

const STAT_SALARY_DEPT = "STAT_SALARY_DEPT";
const STAT_SALARY_WHOLE = "STAT_SALARY_WHOLE";
const STAT_SALARY_BELOW = "STAT_SALARY_BELOW";
const STAT_SALARY_ABOVE = "STAT_SALARY_ABOVE";

const KEYWORDS_GET = "KEYWORDS_GET";
const KEYWORDS_ADD = "KEYWORDS_SET";
const KEYWORDS_DELETE = "KEYWORDS_DELETE";
