const EMP_GET_CATEGORY = "EMP_GET_CATEGORY";
const EMP_SEARCH_NAME = "EMP_SEARCH_NAME";
const EMP_SEARCH_CATEGORY = "EMP_SEARCH_CATEGORY";
const EMP_SET_DATA = "EMP_SET_DATA";
const EMP_FETCH_START = "EMP_FETCH_START";
const EMP_FETCH_FAIL = "EMP_FETCH_FAIL";
const EMP_INIT_BOARD = "EMP_INIT_BOARD";
const EMP_INIT_ERR = "EMP_INIT_ERR";
const EMP_INIT_CATEGORY = "EMP_INIT_CATEGORY";
const EMP_ADD_PAGE = "EMP_ADD_PAGE";

const EMP_RANK_PERIOD = "EMP_RANK_PERIOD";
const EMP_RANK_SALARY = "EMP_RANK_SALARY";
const EMP_HISTORY = "EMP_HISTORY";

const STAT_SALARY_DEPT = "STAT_SALARY_DEPT";
const STAT_SALARY_WHOLE = "STAT_SALARY_WHOLE";
const STAT_SALARY_BELOW = "STAT_SALARY_BELOW";
const STAT_SALARY_ABOVE = "STAT_SALARY_ABOVE";

const KEYWORDS_INIT = "KEYWORDS_INIT";
const KEYWORDS_ADD = "KEYWORDS_SET";
const KEYWORDS_DELETE = "KEYWORDS_DELETE";
