const EMP_SEARCH_NAME = "EMP_SEARCH_NAME";
const EMP_SEARCH_CATEGORY = "EMP_SEARCH_CATEGORY";
const EMP_SET_DATA = "EMP_SET_DATA";
const EMP_FETCH_START = "EMP_FETCH_START";
const EMP_FETCH_FAIL = "EMP_FETCH_FAIL";
const EMP_INIT_BOARD = "EMP_INIT_BOARD";
const EMP_INIT_ERR = "EMP_INIT_ERR";
const EMP_INIT_CATEGORY = "EMP_INIT_CATEGORY";
const EMP_ADD_PAGE = "EMP_ADD_PAGE";

const BAR_INIT_CATEGORY = " BAR_INIT_CATEGORY";
const BAR_SET_OPTION = "BAR_SET_OPTION";
const BAR_OPT_VAL = "BAR_OPT_VAL";
const BAR_INP_VAL = "BAR_INP_VAL";

const KEYWORDS_INIT = "KEYWORDS_INIT";
const KEYWORDS_ADD = "KEYWORDS_SET";
const KEYWORDS_DELETE = "KEYWORDS_DELETE";
